/*CREACION DE TABLAS DEL NEGOCIO ALOHANDES*/
CREATE TABLE OPERADOR
    (
        ID_OPERADOR VARCHAR2(11) CHECK (LENGTH(ID_OPERADOR)>9), 
        NOMBRE_OPERADOR VARCHAR2(32) NOT NULL,
        TIPO_VINCULO_OPERADOR VARCHAR2(20) CHECK (TIPO_VINCULO_OPERADOR IN ('ESTUDIANTE','PROFESOR','PROFESOR_INVITADO','EGRESADO','EMPLEADO','FAMILIA_ESTUDIANTE','REGISTRADO_EVENTO','EMPRESA'))NOT NULL,
        HORA_APERTURA VARCHAR2(32) NOT NULL,
        HORA_CIERRE VARCHAR2(32) NOT NULL,
        DINERO_RECAUDADO NUMBER(20) NOT NULL,
        CORREO_OPERADOR VARCHAR2(32) NOT NULL UNIQUE,
        TELEFONO_OPERADOR NUMBER(15) NOT NULL,
        TIPO_OPERADOR VARCHAR2(20) CHECK (TIPO_OPERADOR IN ('PERSONA_NATURAL','HOTEL','HOSTEL','ALOHA')) NOT NULL,
        CONSTRAINT  OPERADOR_PK PRIMARY KEY (ID_OPERADOR)
    );    
CREATE TABLE CLIENTE
    (
        ID_CLIENTE VARCHAR2(11) CHECK (LENGTH(ID_CLIENTE)>9),
        NOMBRE_CLIENTE VARCHAR2(32) NOT NULL,
        CEDULA_CLIENTE NUMBER(11) NOT NULL UNIQUE,
        HABILITADO_CLIENTE NUMBER(1) NOT NULL CHECK(HABILITADO_CLIENTE IN(0,1)),
        TELEFONO_CLIENTE NUMBER(10)NOT NULL UNIQUE,
        CORREO_CLIENTE VARCHAR2(32) NOT NULL UNIQUE,
        TIPO_VINCULO_CLIENTE VARCHAR2(20) CHECK (TIPO_VINCULO_CLIENTE IN ('ESTUDIANTE','PROFESOR','PROFESOR_INVITADO','EGRESADO','EMPLEADO','FAMILIA_ESTUDIANTE','REGISTRADO_EVENTO','EMPRESA'))NOT NULL
   ,      CONSTRAINT  CLIENTE_PK PRIMARY KEY (ID_CLIENTE)
    );
CREATE TABLE PAGO
    (
        ID_PAGO NUMBER(32) PRIMARY KEY,
        FECHA_PAGO DATE NOT NULL,
        ID_RESERVA NUMBER(32) NOT NULL,
        MONTO NUMBER(20)        
     );
ALTER TABLE PAGO  ADD CONSTRAINT RESERVA_FK FOREIGN KEY(ID_RESERVA)REFERENCES RESERVA(ID_RESERVA);

CREATE TABLE RESERVA
    (
        ID_RESERVA NUMBER(32) PRIMARY KEY ,
        FECHA_INICIO_RESERVA DATE NOT NULL,
        FECHA_FINAL_RESERVA DATE NOT NULL,
        FECHA_GENERACION_RESERVA DATE NOT NULL,
        CANCELADO CHAR(1) CHECK (CANCELADO in ('Y','N')) NOT NULL,
        FECHA_CANCELACION DATE,
        NUMERO_PERSONAS NUMBER(2) NOT NULL,
        ID_CLIENTE VARCHAR2(11) CHECK (LENGTH(ID_CLIENTE)>9),
        ID_INMUEBLE NUMBER(11)NOT NULL
        
    );
ALTER TABLE RESERVA ADD  CONSTRAINT INMUEBLE_FK FOREIGN KEY (ID_INMUEBLE)REFERENCES INMUEBLE(ID_INMUEBLE);
ALTER TABLE RESERVA ADD  CONSTRAINT CLIENTE_FK FOREIGN KEY (ID_CLIENTE)REFERENCES CLIENTE(ID_CLIENTE);

CREATE TABLE CXC
    (
        ID_RESERVA NUMBER(32),
        MONTO NUMBER(10),
     CONSTRAINT CXC_PK PRIMARY KEY (ID_RESERVA)
        );
        
ALTER TABLE CXC ADD CONSTRAINT FK_RESERVA FOREIGN KEY(ID_RESERVA) REFERENCES RESERVA(ID_RESERVA);

CREATE TABLE INMUEBLE
(
   ID_INMUEBLE NUMBER(11),
   DISPONIBLE CHAR(1) CHECK (DISPONIBLE in ('Y','N')) NOT NULL,
   NOMBRE VARCHAR2(30) NOT NULL,
   TIPO_INMUEBLE VARCHAR2(30) CHECK ( TIPO_INMUEBLE IN('HABITACION_HOSTEL','HABITACION_HOTEL','HABITACION_PERSONA_NATURAL','APARTAMENTO','HABITACION_UNIVERSITARIA','VIVIENDA_CEDIDA')) NOT NULL, 
   UBICACION VARCHAR2(30) NOT NULL,
   CAPACIDAD NUMBER(11)NOT NULL,
   DESCRIPCION VARCHAR2(500) NOT NULL ,
   VECES_RESERVADA NUMBER(11) NOT NULL,
   COSTO_NOCHE NUMBER(11)NOT NULL,
   ID_OPERADOR VARCHAR2(11) CHECK(LENGTH(ID_OPERADOR) >9),
   CONSTRAINT INMUEBLE_PK PRIMARY KEY(ID_INMUEBLE)
   );
   
ALTER TABLE INMUEBLE ADD CONSTRAINT FK_INM_OPER FOREIGN KEY (ID_OPERADOR) REFERENCES OPERADOR (ID_OPERADOR);
ALTER TABLE INMUEBLE ADD CONSTRAINT FK_RESTRI_INM FOREIGN KEY (TIPO_INMUEBLE) REFERENCES RESTRICCION_INMUEBLE (TIPO_INMUEBLE);

CREATE  TABLE HABITACION_PERSONA_NATURAL
(
   PRECIO_SERIVICIOS INTEGER NOT NULL,
   COMIDA_INCLUIDA CHAR(1) CHECK (COMIDA_INCLUIDA in ('Y','N')) NOT NULL,
   BAÑO_PRIVADO CHAR(1) CHECK (BAÑO_PRIVADO in ('Y','N')) NOT NULL,
   COCINETA CHAR(1) CHECK (COCINETA in ('Y','N')) NOT NULL,
   COMPARTIDA CHAR(1) CHECK (COMPARTIDA in ('Y','N')) NOT NULL,
   ID_INMUEBLE_PR  NUMBER(11) ,
   CONSTRAINT PK_HABITACION_PERSONA  PRIMARY KEY (ID_INMUEBLE_PR)
   );
   
ALTER TABLE HABITACION_PERSONA_NATURAL ADD CONSTRAINT FK_HABITACION_PERSO_INM FOREIGN KEY (ID_INMUEBLE_PR) REFERENCES INMUEBLE (ID_INMUEBLE);

CREATE TABLE HABITACION_HOSTEL
(
COMPARTIDA CHAR(1) CHECK (COMPARTIDA in ('Y','N')) NOT NULL,
ID_INMUEBLE_HSH  NUMBER(11), 
CONSTRAINT PK_HABITACION_HOSTEL  PRIMARY KEY (ID_INMUEBLE_HSH)
);

ALTER TABLE HABITACION_HOSTEL ADD CONSTRAINT FK_HABITACION_HOSTEL_INM FOREIGN KEY (ID_INMUEBLE_HSH) REFERENCES INMUEBLE (ID_INMUEBLE);

CREATE TABLE HABITACION_HOTEL
(
TIPO_HABITACION VARCHAR2(30) CHECK ( TIPO_HABITACION IN ('ESTANDAR','SUITE','SEMISUITE')) NOT NULL,
COSTO_TOTAL INTEGER NOT NULL, 
ID_INMUEBLE_HH  NUMBER(11), 
CONSTRAINT PK_HABITACION_HOTEL  PRIMARY KEY (ID_INMUEBLE_HH)
);

ALTER TABLE HABITACION_HOTEL ADD CONSTRAINT FK_HABITACION_HOTEL_INM FOREIGN KEY (ID_INMUEBLE_HH) REFERENCES INMUEBLE (ID_INMUEBLE);

CREATE TABLE APARTAMENTO
(
NUMERO_HABITACIONES INTEGER NOT NULL,
AMOBLADO CHAR(1) CHECK (AMOBLADO in ('Y','N')) NOT NULL,
SERVICIOS_INCLUIDOS CHAR(1) CHECK (SERVICIOS_INCLUIDOS in ('Y','N')) NOT NULL,
ID_INMUEBLE_AP  NUMBER(11), 
CONSTRAINT PK_HABITACION_AP  PRIMARY KEY (ID_INMUEBLE_AP)
);

ALTER TABLE APARTAMENTO ADD CONSTRAINT FK_APARTAMENTO_INM FOREIGN KEY (ID_INMUEBLE_AP) REFERENCES INMUEBLE (ID_INMUEBLE);

CREATE TABLE VIVIENDA_CEDIDA
(
DIAS_USADO_AÑO INTEGER NOT NULL,
SEGURO CHAR(500) NOT NULL,
ID_INMUEBLE_VC  NUMBER(11), 
CONSTRAINT PK_VIVIENDA_CEDIDA PRIMARY KEY (ID_INMUEBLE_VC)
);

ALTER TABLE VIVIENDA_CEDIDA ADD CONSTRAINT FK_VIVIENDA_CEDIDA_INM FOREIGN KEY (ID_INMUEBLE_VC) REFERENCES INMUEBLE (ID_INMUEBLE);

CREATE TABLE HABITACION_UNIVERSITARIA
(
COMPARTIDA CHAR(1) CHECK (COMPARTIDA in ('Y','N')) NOT NULL,
AMOBALADA CHAR(1) CHECK (AMOBALADA in ('Y','N')) NOT NULL,
ID_INMUEBLE_HU  NUMBER(11), 
CONSTRAINT PK_HABITACION_UNIVERSITARIAU PRIMARY KEY (ID_INMUEBLE_HU)
);

ALTER TABLE HABITACION_UNIVERSITARIA ADD CONSTRAINT FK_HABITACION_UNI_INM FOREIGN KEY (ID_INMUEBLE_HU) REFERENCES INMUEBLE (ID_INMUEBLE);

CREATE TABLE RESTRICCION_INMUEBLE
(
TIPO_INMUEBLE VARCHAR2(30) CHECK ( TIPO_INMUEBLE IN('HABITACION_HOSTEL','HABITACION_HOTEL','HABITACION_PERSONA_NATURAL','APARTAMENTO','HABITACION_UNIVERSITARIA','VIVIENDA_CEDIDA')) NOT NULL,
DURACION_MINIMA_DIAS NUMERIC(3),
CONSTRAINT PK_RESTRICCION_INMUEBLE PRIMARY KEY (TIPO_INMUEBLE)
);
 

CREATE TABLE SERVICIO_ADICIONAL
(
ID_SERVICIO NUMBER(11),
NOMBRE VARCHAR2(30) NOT NULL,
COSTO NUMBER(11) NOT NULL,
ID_INMUEBLE_SE NUMBER(11) NOT NULL,
CONSTRAINT PK_SERVICIO PRIMARY KEY (ID_SERVICIO)
)

ALTER TABLE SERVICIO_ADICIONAL
ADD CONSTRAINT FK_SERVI_INM
FOREIGN KEY (ID_INMUEBLE_SE) REFERENCES INMUEBLE (ID_INMUEBLE);

/*POBLACION DE TABLAS*/

INSERT ALL
    INTO OPERADOR (ID_OPERADOR, NOMBRE_OPERADOR, TIPO_VINCULO_OPERADOR, HORA_APERTURA, HORA_CIERRE, DINERO_RECAUDADO, CORREO_OPERADOR, TELEFONO_OPERADOR, TIPO_OPERADOR)
    VALUES ('1007863890','mateo perez', 'ESTUDIANTE', '24H','24H', 0, 'mateoperez0508@uniandes.edu.co', 3144183191, 'PERSONA_NATURAL')
    
    INTO OPERADOR (ID_OPERADOR, NOMBRE_OPERADOR, TIPO_VINCULO_OPERADOR, HORA_APERTURA, HORA_CIERRE, DINERO_RECAUDADO, CORREO_OPERADOR, TELEFONO_OPERADOR, TIPO_OPERADOR)
    VALUES ('1007863891','laura rodriguez', 'PROFESOR', '6:00AM','9:00PM', 0, 'laura@uniandes.edu.co', 3144183192, 'PERSONA_NATURAL')
    
    INTO OPERADOR (ID_OPERADOR, NOMBRE_OPERADOR, TIPO_VINCULO_OPERADOR, HORA_APERTURA, HORA_CIERRE, DINERO_RECAUDADO, CORREO_OPERADOR, TELEFONO_OPERADOR, TIPO_OPERADOR)
    VALUES ('1007863892','crsitian marin', 'EMPLEADO', '6:00AM','9:00PM', 0, 'cristian@uniandes.edu.co', 3144183193, 'PERSONA_NATURAL')
    
    INTO OPERADOR (ID_OPERADOR, NOMBRE_OPERADOR, TIPO_VINCULO_OPERADOR, HORA_APERTURA, HORA_CIERRE, DINERO_RECAUDADO, CORREO_OPERADOR, TELEFONO_OPERADOR, TIPO_OPERADOR)
    VALUES ('1007863893','felipe delgado', 'EGRESADO', '6:00AM','11:00PM',0, 'felipe@uniandes.edu.co', 3144183194, 'PERSONA_NATURAL')
    
    INTO OPERADOR (ID_OPERADOR, NOMBRE_OPERADOR, TIPO_VINCULO_OPERADOR, HORA_APERTURA, HORA_CIERRE, DINERO_RECAUDADO, CORREO_OPERADOR, TELEFONO_OPERADOR, TIPO_OPERADOR)
    VALUES ('1007863894','liviin18', 'EMPRESA', '5:00AM','12:00PM',0, 'liviin18@uniandes.edu.co', 3144183195, 'HOTEL')
    
    INTO OPERADOR (ID_OPERADOR, NOMBRE_OPERADOR, TIPO_VINCULO_OPERADOR, HORA_APERTURA, HORA_CIERRE, DINERO_RECAUDADO, CORREO_OPERADOR, TELEFONO_OPERADOR, TIPO_OPERADOR)
    VALUES ('1007863895','ana leon', 'EMPRESA', '5:00AM','12:00PM',0, 'analeon@uniandes.edu.co', 3144183196, 'HOSTEL')
    
    INTO OPERADOR (ID_OPERADOR, NOMBRE_OPERADOR, TIPO_VINCULO_OPERADOR, HORA_APERTURA, HORA_CIERRE, DINERO_RECAUDADO, CORREO_OPERADOR, TELEFONO_OPERADOR, TIPO_OPERADOR)
    VALUES ('1007863896','livin21', 'EMPRESA', '5:00AM','12:00PM',0, 'liviin21@uniandes.edu.co', 3144183197, 'ALOHA')
    
    INTO OPERADOR (ID_OPERADOR, NOMBRE_OPERADOR, TIPO_VINCULO_OPERADOR, HORA_APERTURA, HORA_CIERRE, DINERO_RECAUDADO, CORREO_OPERADOR, TELEFONO_OPERADOR, TIPO_OPERADOR)
    VALUES ('1007863897','martin reckless', 'ESTUDIANTE', '6:00AM','6:00AM',0, 'martin@uniandes.edu.co', 3144183198, 'PERSONA_NATURAL')
    
    INTO OPERADOR (ID_OPERADOR, NOMBRE_OPERADOR, TIPO_VINCULO_OPERADOR, HORA_APERTURA, HORA_CIERRE, DINERO_RECAUDADO, CORREO_OPERADOR, TELEFONO_OPERADOR, TIPO_OPERADOR)
    VALUES ('1007863898','cityu', 'EMPRESA', '5:00AM','12:00PM',0, 'cityu@uniandes.edu.co', 3144183121, 'ALOHA')
        
    INTO OPERADOR (ID_OPERADOR, NOMBRE_OPERADOR, TIPO_VINCULO_OPERADOR, HORA_APERTURA, HORA_CIERRE, DINERO_RECAUDADO, CORREO_OPERADOR, TELEFONO_OPERADOR, TIPO_OPERADOR)
    VALUES ('1007863899','cityu', 'EMPRESA', '5:00AM','12:00PM',0, 'citMyu@uniandes.edu.co', 3146753121, 'ALOHA')
    
 SELECT * FROM DUAL;
 
INSERT ALL
    INTO CLIENTE (ID_CLIENTE, NOMBRE_CLIENTE, CEDULA_CLIENTE,HABILITADO_CLIENTE, TELEFONO_CLIENTE, CORREO_CLIENTE, TIPO_VINCULO_CLIENTE)
    VALUES('1007863890', 'CRISTIAN MARIN',1007863890,1,3144183191, 'CORREO@UNIANDES.EDU.CO','ESTUDIANTE')
    
    INTO CLIENTE (ID_CLIENTE, NOMBRE_CLIENTE, CEDULA_CLIENTE,HABILITADO_CLIENTE, TELEFONO_CLIENTE, CORREO_CLIENTE, TIPO_VINCULO_CLIENTE)
    VALUES('1007863891', 'RAMIRO PEREZ',1007863891,1,3144183190, 'CORREO1@UNIANDES.EDU.CO','PROFESOR')
     
    INTO CLIENTE (ID_CLIENTE, NOMBRE_CLIENTE, CEDULA_CLIENTE,HABILITADO_CLIENTE, TELEFONO_CLIENTE, CORREO_CLIENTE, TIPO_VINCULO_CLIENTE)
    VALUES('1007863892', 'ALFARI ARIAS',1007863892,1,3144183192, 'ALFARI@UNIANDES.EDU.CO','PROFESOR_INVITADO')
    
    INTO CLIENTE (ID_CLIENTE, NOMBRE_CLIENTE, CEDULA_CLIENTE,HABILITADO_CLIENTE, TELEFONO_CLIENTE, CORREO_CLIENTE, TIPO_VINCULO_CLIENTE)
    VALUES('1007863893', 'PERKS DIAZ',1007863893,0,3144183193, 'PERKS@UNIANDES.EDU.CO','EGRESADO')
 
    INTO CLIENTE (ID_CLIENTE, NOMBRE_CLIENTE, CEDULA_CLIENTE, HABILITADO_CLIENTE,TELEFONO_CLIENTE, CORREO_CLIENTE, TIPO_VINCULO_CLIENTE)
    VALUES('1007863894', 'FAKER KUN',1007863894,0,3144183194, 'FAKSER@UNIANDES.EDU.CO','EMPLEADO')
 
    INTO CLIENTE (ID_CLIENTE, NOMBRE_CLIENTE, CEDULA_CLIENTE,HABILITADO_CLIENTE, TELEFONO_CLIENTE, CORREO_CLIENTE, TIPO_VINCULO_CLIENTE)
    VALUES('1007863895', 'LEE SIN',1007863895,1,3144183195, 'LEESIN@UNIANDES.EDU.CO','FAMILIA_ESTUDIANTE')
 
    INTO CLIENTE (ID_CLIENTE, NOMBRE_CLIENTE, CEDULA_CLIENTE, HABILITADO_CLIENTE,TELEFONO_CLIENTE, CORREO_CLIENTE, TIPO_VINCULO_CLIENTE)
    VALUES('1007863896', 'IAN REMIREZ',1007863896,1,3144183196, 'IANR@UNIANDES.EDU.CO','REGISTRADO_EVENTO')
 
    INTO CLIENTE (ID_CLIENTE, NOMBRE_CLIENTE, CEDULA_CLIENTE,HABILITADO_CLIENTE, TELEFONO_CLIENTE, CORREO_CLIENTE, TIPO_VINCULO_CLIENTE)
    VALUES('1007863897', 'LUCAS MARTINEZ',1007863897,1,3144183197, 'LUCAS@UNIANDES.EDU.CO','ESTUDIANTE')
 
    INTO CLIENTE (ID_CLIENTE, NOMBRE_CLIENTE, CEDULA_CLIENTE,HABILITADO_CLIENTE, TELEFONO_CLIENTE, CORREO_CLIENTE, TIPO_VINCULO_CLIENTE)
    VALUES('1007863898', 'ELVER GALARGA',1007863898,0,3144183198, 'ELVERGALARGA@UNIANDES.EDU.CO','ESTUDIANTE')
    
 
 SELECT * FROM DUAL;
 
INSERT ALL
    INTO RESERVA (ID_RESERVA,FECHA_INICIO_RESERVA,FECHA_FINAL_RESERVA,FECHA_GENERACION_RESERVA,FECHA_CANCELACION,CANCELADO,NUMERO_PERSONAS,ID_CLIENTE,ID_INMUEBLE)
    VALUES (2234567898,DATE'2015-12-17',DATE'2016-1-17',DATE'2019-12-17',DATE'2015-12-17','N',1,1007863890,1)
    INTO RESERVA (ID_RESERVA,FECHA_INICIO_RESERVA,FECHA_FINAL_RESERVA,FECHA_GENERACION_RESERVA,FECHA_CANCELACION,CANCELADO,NUMERO_PERSONAS,ID_CLIENTE,ID_INMUEBLE)
    VALUES (1234567899,DATE'2015-12-17',DATE'2016-1-17',DATE'2019-12-17',DATE'2015-12-17','N',4,1007863891,2)
    INTO RESERVA (ID_RESERVA,FECHA_INICIO_RESERVA,FECHA_FINAL_RESERVA,FECHA_GENERACION_RESERVA,FECHA_CANCELACION,CANCELADO,NUMERO_PERSONAS,ID_CLIENTE,ID_INMUEBLE)
    VALUES (1234567897,DATE'2015-12-17',DATE'2016-1-17',DATE'2019-12-17',DATE'2015-12-17','N',12,1007863892,3)
    INTO RESERVA (ID_RESERVA,FECHA_INICIO_RESERVA,FECHA_FINAL_RESERVA,FECHA_GENERACION_RESERVA,FECHA_CANCELACION,CANCELADO,NUMERO_PERSONAS,ID_CLIENTE,ID_INMUEBLE)
    VALUES (1234567896,DATE'2015-12-17',DATE'2016-1-17',DATE'2019-12-17',DATE'2015-12-17','N',13,1007863893,4)
    INTO RESERVA (ID_RESERVA,FECHA_INICIO_RESERVA,FECHA_FINAL_RESERVA,FECHA_GENERACION_RESERVA,FECHA_CANCELACION,CANCELADO,NUMERO_PERSONAS,ID_CLIENTE,ID_INMUEBLE)
    VALUES (1234567895,DATE'2015-12-17',DATE'2016-1-17',DATE'2019-12-17',DATE'2015-12-17','N',7,1007863894,5)
    INTO RESERVA (ID_RESERVA,FECHA_INICIO_RESERVA,FECHA_FINAL_RESERVA,FECHA_GENERACION_RESERVA,FECHA_CANCELACION,CANCELADO,NUMERO_PERSONAS,ID_CLIENTE,ID_INMUEBLE)
    VALUES (1234567894,DATE'2015-12-17',DATE'2016-1-17',DATE'2020-12-17',DATE'2015-12-17','N',2,1007863895,6)
    INTO RESERVA (ID_RESERVA,FECHA_INICIO_RESERVA,FECHA_FINAL_RESERVA,FECHA_GENERACION_RESERVA,FECHA_CANCELACION,CANCELADO,NUMERO_PERSONAS,ID_CLIENTE,ID_INMUEBLE)
    VALUES (1234567893,DATE'2015-12-17',DATE'2016-1-17',DATE'2020-12-17',DATE'2015-12-17','N',2,1007863896,7)
    INTO RESERVA (ID_RESERVA,FECHA_INICIO_RESERVA,FECHA_FINAL_RESERVA,FECHA_GENERACION_RESERVA,FECHA_CANCELACION,CANCELADO,NUMERO_PERSONAS,ID_CLIENTE,ID_INMUEBLE)
    VALUES (1234567843,DATE'2015-12-17',DATE'2016-1-17',DATE'2020-12-17',DATE'2015-12-17','N',2,1007863898,4)
    
    SELECT * FROM DUAL;
    
INSERT ALL
    INTO PAGO (ID_PAGO,FECHA_PAGO  , ID_RESERVA )
    VALUES(1,DATE'2015-12-17', 2234567898)
    INTO PAGO (ID_PAGO,FECHA_PAGO  , ID_RESERVA )
    VALUES(2,DATE'2015-12-17', 1234567899)
    INTO PAGO (ID_PAGO,FECHA_PAGO  , ID_RESERVA )
    VALUES(3,DATE'2015-12-17', 1234567897)
        INTO PAGO (ID_PAGO,FECHA_PAGO  , ID_RESERVA )
    VALUES(4,DATE'2015-12-17', 1234567896)
    INTO PAGO (ID_PAGO,FECHA_PAGO  , ID_RESERVA )
    VALUES(5,DATE'2015-12-17', 1234567895)
    INTO PAGO (ID_PAGO,FECHA_PAGO  , ID_RESERVA )
    VALUES(6,DATE'2015-12-17', 1234567893)
    INTO PAGO (ID_PAGO,FECHA_PAGO  , ID_RESERVA )
    VALUES(7,DATE'2015-12-17', 1234567894)
    INTO PAGO (ID_PAGO,FECHA_PAGO  , ID_RESERVA )
    VALUES(8,DATE'2015-12-17', 1234567843)

SELECT * FROM DUAL;
INSERT ALL
    INTO CXC (ID_RESERVA,MONTO)
    VALUES(2234567898,123456643)
        INTO CXC (ID_RESERVA,MONTO)
    VALUES(1234567899,123423665)
        INTO CXC (ID_RESERVA,MONTO)
    VALUES(1234567897,123458765)
        INTO CXC (ID_RESERVA,MONTO)
    VALUES(1234567896,100000)
        INTO CXC (ID_RESERVA,MONTO)
    VALUES(1234567895,12345676)
        INTO CXC (ID_RESERVA,MONTO)
    VALUES(1234567894,12345601)
        INTO CXC (ID_RESERVA,MONTO)
    VALUES(1234567893,21345665)
    INTO CXC (ID_RESERVA,MONTO)
    VALUES(1234567843,50000)
    
    
SELECT * FROM DUAL;
DELETE  FROM INMUEBLE;
INSERT ALL
INTO INMUEBLE (ID_INMUEBLE, DISPONIBLE,NOMBRE,TIPO_INMUEBLE,UBICACION,CAPACIDAD,DESCRIPCION,VECES_RESERVADA,COSTO_NOCHE,ID_OPERADOR)
VALUES (1, 'Y','APARTAMENTO DE JOSE','APARTAMENTO','CRA 34 #23C-76',8,'APARTAMENO 5 ALCOBAS Y COCINA',6,300,'1007863890')

INTO INMUEBLE (ID_INMUEBLE, DISPONIBLE,NOMBRE,TIPO_INMUEBLE,UBICACION,CAPACIDAD,DESCRIPCION,VECES_RESERVADA,COSTO_NOCHE,ID_OPERADOR)
VALUES (2, 'Y','HABITACION_HILTON','HABITACION_HOTEL','CRA 40 #25C-12',5,'4 CAMAS Y DOS BAÑOS',5,100,'1007863891')

INTO INMUEBLE (ID_INMUEBLE, DISPONIBLE,NOMBRE,TIPO_INMUEBLE,UBICACION,CAPACIDAD,DESCRIPCION,VECES_RESERVADA,COSTO_NOCHE,ID_OPERADOR)
VALUES (3, 'Y','HABITACION DE PABLO','HABITACION_PERSONA_NATURAL','CRA 20 #29C-76',1,'1 BAÑO Y UNA CAMA',3,50,'1007863892')

INTO INMUEBLE (ID_INMUEBLE, DISPONIBLE,NOMBRE,TIPO_INMUEBLE,UBICACION,CAPACIDAD,DESCRIPCION,VECES_RESERVADA,COSTO_NOCHE,ID_OPERADOR)
VALUES (4, 'Y','HABITACION BUEN VIVIR','HABITACION_HOSTEL','CRA 70 60C-76',3,'3 CAMAS 2 BAÑOS',7,80,'1007863893')

INTO INMUEBLE (ID_INMUEBLE, DISPONIBLE,NOMBRE,TIPO_INMUEBLE,UBICACION,CAPACIDAD,DESCRIPCION,VECES_RESERVADA,COSTO_NOCHE,ID_OPERADOR)
VALUES (5, 'Y','HABITACION ALOHA','HABITACION_UNIVERSITARIA','CRA 10 #19C-76',1,'1 CAMA 1 BAÑO',4,150,'1007863894')

INTO INMUEBLE (ID_INMUEBLE, DISPONIBLE,NOMBRE,TIPO_INMUEBLE,UBICACION,CAPACIDAD,DESCRIPCION,VECES_RESERVADA,COSTO_NOCHE,ID_OPERADOR)
VALUES (6, 'Y','VIVIENDA DE JAVIER','VIVIENDA_CEDIDA','CRA 45 #12C-45',5,'3 PISOS 4 HABITACIONES CON CAMA CADA UNA',2,350,'1007863895')

INTO INMUEBLE (ID_INMUEBLE, DISPONIBLE,NOMBRE,TIPO_INMUEBLE,UBICACION,CAPACIDAD,DESCRIPCION,VECES_RESERVADA,COSTO_NOCHE,ID_OPERADOR)
VALUES (7, 'Y','VIVIENDA DE ZONIA','VIVIENDA_CEDIDA','CRA 70 #156C-45',5,'2 PISOS 4 HABITACIONES CON CAMA CADA UNA',2,320,'1007863896')

INTO INMUEBLE (ID_INMUEBLE, DISPONIBLE,NOMBRE,TIPO_INMUEBLE,UBICACION,CAPACIDAD,DESCRIPCION,VECES_RESERVADA,COSTO_NOCHE,ID_OPERADOR)
VALUES (8, 'Y','HABITACION_HOLADYINN','HABITACION_HOTEL','CRA 20 #26C-45',2,'2 CAMAS CON BAÑO',2,120,'1007863897')

INTO INMUEBLE (ID_INMUEBLE, DISPONIBLE,NOMBRE,TIPO_INMUEBLE,UBICACION,CAPACIDAD,DESCRIPCION,VECES_RESERVADA,COSTO_NOCHE,ID_OPERADOR)
VALUES (9, 'Y','APARTAMENTO DE JOSE','APARTAMENTO','CRA 45 #12C-45',6,'3 HABITACIONES 2 BAÑOS',5,250,'1007863898')

INTO INMUEBLE (ID_INMUEBLE, DISPONIBLE,NOMBRE,TIPO_INMUEBLE,UBICACION,CAPACIDAD,DESCRIPCION,VECES_RESERVADA,COSTO_NOCHE,ID_OPERADOR)
VALUES (10, 'Y','HABITACION BUEN VIVIR','HABITACION_HOSTEL','CRA 26 #68C-45',2,'2 CAMAS UN BAÑO',2,150,'1007863899')
SELECT * FROM dual;

INSERT INTO HABITACION_PERSONA_NATURAL (PRECIO_SERIVICIOS,COMIDA_INCLUIDA,BAÑO_PRIVADO,COCINETA,COMPARTIDA,  ID_INMUEBLE_PR)
VALUES(400,'N','Y','Y','N',3);

INSERT ALL
INTO HABITACION_HOSTEL (COMPARTIDA,ID_INMUEBLE_HSH)
VALUES('Y',4)
INTO HABITACION_HOSTEL (COMPARTIDA,ID_INMUEBLE_HSH)
VALUES('Y',10)
SELECT * FROM dual;

INSERT ALL
INTO HABITACION_HOTEL (TIPO_HABITACION,COSTO_TOTAL,ID_INMUEBLE_HH)
VALUES('ESTANDAR',237,2)
INTO HABITACION_HOTEL (TIPO_HABITACION,COSTO_TOTAL,ID_INMUEBLE_HH)
VALUES('SUITE',345,8)
SELECT * FROM dual;

INSERT ALL
INTO APARTAMENTO (NUMERO_HABITACIONES,AMOBLADO,SERVICIOS_INCLUIDOS,ID_INMUEBLE_AP)
VALUES(5,'N','N',1)
INTO APARTAMENTO (NUMERO_HABITACIONES,AMOBLADO,SERVICIOS_INCLUIDOS,ID_INMUEBLE_AP)
VALUES(3,'Y','N',9)
SELECT * FROM dual;

INSERT ALL
INTO VIVIENDA_CEDIDA (DIAS_USADO_AÑO,SEGURO,ID_INMUEBLE_VC)
VALUES(5,'INFO SEGURO COLSEGUROS',6)
INTO VIVIENDA_CEDIDA (DIAS_USADO_AÑO,SEGURO,ID_INMUEBLE_VC)
VALUES(3,'INFO SEGURO MAPFRE',7)
SELECT * FROM dual;

INSERT INTO HABITACION_UNIVERSITARIA (COMPARTIDA,AMOBALADA, ID_INMUEBLE_HU)
VALUES('N','Y',5);

INSERT INTO RESTRICCION_INMUEBLE (TIPO_INMUEBLE,DURACION_MINIMA_DIAS)
VALUES ('HABITACION_HOSTEL',10);
INSERT INTO RESTRICCION_INMUEBLE (TIPO_INMUEBLE,DURACION_MINIMA_DIAS)
VALUES ('HABITACION_HOTEL',20);
INSERT INTO RESTRICCION_INMUEBLE (TIPO_INMUEBLE,DURACION_MINIMA_DIAS)
VALUES ('HABITACION_PERSONA_NATURAL',30);
INSERT INTO RESTRICCION_INMUEBLE (TIPO_INMUEBLE,DURACION_MINIMA_DIAS)
VALUES ('APARTAMENTO',5);
INSERT INTO RESTRICCION_INMUEBLE (TIPO_INMUEBLE,DURACION_MINIMA_DIAS)
VALUES ('HABITACION_UNIVERSITARIA',7);
INSERT INTO RESTRICCION_INMUEBLE (TIPO_INMUEBLE,DURACION_MINIMA_DIAS)
VALUES ('VIVIENDA_CEDIDA',6);


INSERT ALL
INTO SERVICIO_ADICIONAL (ID_SERVICIO,COSTO,NOMBRE,ID_INMUEBLE_SE)
VALUES(135453,30,'SPA',2)
INTO SERVICIO_ADICIONAL (ID_SERVICIO,COSTO,NOMBRE,ID_INMUEBLE_SE)
VALUES(256456,27,'SAUNA',2)
INTO SERVICIO_ADICIONAL (ID_SERVICIO,COSTO,NOMBRE,ID_INMUEBLE_SE)
VALUES(3345345,20,'PISCINA',2)
INTO SERVICIO_ADICIONAL (ID_SERVICIO,COSTO,NOMBRE,ID_INMUEBLE_SE)
VALUES(5464564,0,'SALAS DE ESTUDIO',5)
INTO SERVICIO_ADICIONAL (ID_SERVICIO,COSTO,NOMBRE,ID_INMUEBLE_SE)
VALUES(53453,40,'RESTAURANTE',2)
INTO SERVICIO_ADICIONAL (ID_SERVICIO,COSTO,NOMBRE,ID_INMUEBLE_SE)
VALUES(6567567,10,'GIMNASIO',5)
INTO SERVICIO_ADICIONAL (ID_SERVICIO,COSTO,NOMBRE,ID_INMUEBLE_SE)
VALUES(34534,20,'RESTAURANTE',5)
SELECT * FROM dual;


/*CONSULTAS */
SELECT * FROM OPERADOR;
SELECT * FROM CLIENTE;
SELECT * FROM RESERVA;
SELECT * FROM PAGO;
SELECT * FROM CXC;

SELECT * FROM INMUEBLE;
SELECT * FROM APARTAMENTO;
SELECT * FROM HABITACION_HOSTEL;
SELECT * FROM HABITACION_HOTEL;
SELECT * FROM HABITACION_PERSONA_NATURAL;
SELECT * FROM HABITACION_UNIVERSITARIA;
SELECT * FROM VIVIENDA_CEDIDA;
SELECT * FROM RESTRICCION_INMUEBLE;

/*ELIMINACION DE TABLAS*/
DROP TABLE CXC;      
DROP TABLE OPERADOR;
DROP TABLE CLIENTE;
DROP TABLE PAGO;
DROP TABLE RESERVA;

DROP TABLE INMUEBLE;
DROP TABLE APARTAMENTO;
DROP TABLE HABITACION_HOSTEL;
DROP TABLE HABITACION_HOTEL;
DROP TABLE HABITACION_PERSONA_NATURAL;
DROP TABLE HABITACION_UNIVERSITARIA;
DROP TABLE VIVIENDA_CEDIDA;
DROP TABLE RESTRICCION_INMUEBLE;
DROP TABLE SERVICIO_ADICIONAL;
/*ELIMINACION FILAS EN TABLAS*/
DELETE FROM RESERVA;
DELETE FROM OPERADOR;
DELETE FROM PAGO;
DELETE FROM CXC;
DELETE FROM INMUEBLE;
DELETE FROM APARTAMENTO;
DELETE FROM HABITACION_HOSTEL;
DELETE FROM HABITACION_HOTEL;
DELETE FROM HABITACION_PERSONA_NATURAL;
DELETE FROM HABITACION_UNIVERSITARIA;
DELETE FROM RESTRICCION_INMUEBLE;
DELETE FROM VIVIENDA_CEDIDA;
DELETE FROM SERVICIO_ADICIONAL;


/////////////////////////////REQUERIMIENTO DE CONSLTA/////////////////////

//RFC1

SELECT OPA,AÑO_CORRIDO,AÑO_ACTUAL FROM
(select INMUEBLE.ID_OPERADOR AS OPA ,sum(monto) as AÑO_CORRIDO
from INMUEBLE,OPERADOR,RESERVA,CXC
where inmueble.id_operador = operador.id_operador 
and inmueble.id_inmueble = reserva.id_inmueble
AND RESERVA.ID_RESERVA = CXC.ID_RESERVA
AND FECHA_GENERACION_RESERVA < (DATE'2019-12-31') AND FECHA_GENERACION_RESERVA > (DATE'2019-01-1')
group by INMUEBLE.ID_OPERADOR)A LEFT OUTER JOIN

(select INMUEBLE.ID_OPERADOR AS OPB,sum(monto) as AÑO_ACTUAL
from INMUEBLE,OPERADOR  ,RESERVA,CXC
where inmueble.id_operador = operador.id_operador 
and inmueble.id_inmueble = reserva.id_inmueble
AND RESERVA.ID_RESERVA = CXC.ID_RESERVA
AND FECHA_GENERACION_RESERVA > (DATE'2019-12-31')
group by INMUEBLE.ID_OPERADOR)B
ON A.OPA = B.OPB 
UNION
SELECT OPB,AÑO_CORRIDO,AÑO_ACTUAL FROM
(
select INMUEBLE.ID_OPERADOR AS OPA ,sum(monto) as AÑO_CORRIDO
from INMUEBLE,OPERADOR,RESERVA,CXC
where inmueble.id_operador = operador.id_operador 
and inmueble.id_inmueble = reserva.id_inmueble
AND RESERVA.ID_RESERVA = CXC.ID_RESERVA
AND FECHA_GENERACION_RESERVA < (DATE'2019-12-31') AND FECHA_GENERACION_RESERVA > (DATE'2019-01-1')
group by INMUEBLE.ID_OPERADOR)A RIGHT OUTER JOIN

(select INMUEBLE.ID_OPERADOR AS OPB,sum(monto) as AÑO_ACTUAL
from INMUEBLE,OPERADOR  ,RESERVA,CXC
where inmueble.id_operador = operador.id_operador 
and inmueble.id_inmueble = reserva.id_inmueble
AND RESERVA.ID_RESERVA = CXC.ID_RESERVA
AND FECHA_GENERACION_RESERVA > (DATE'2019-12-31')
group by INMUEBLE.ID_OPERADOR)B
ON A.OPA = B.OPB 

//RFC2

SELECT ID_INMUEBLE,NOMBRE,VECES_RESERVADA 
FROM INMUEBLE
WHERE ROWNUM <=20
GROUP BY ID_INMUEBLE,NOMBRE,VECES_RESERVADA
ORDER BY VECES_RESERVADA DESC


//BONO REQUERIMIENTO RFC4 , PARA QUE FUNCIONE DEBE MODIFICAR LAS FEHCAS Y LOS SERVICIOS ADICIONALES QUE SE QUIERAN

SELECT INMUEBLES FROM(
SELECT RESERVA.ID_INMUEBLE AS INMUEBLES_RESERVADOS FROM RESERVA WHERE  FECHA_INICIO_RESERVA > (DATE'2020-12-31') AND FECHA_FINAL_RESERVA < (DATE'2021-01-1')  ) RIGHT OUTER JOIN(

SELECT INMUEBLE.ID_INMUEBLE AS INMUEBLES FROM INMUEBLE,SERVICIO_ADICIONAL
WHERE INMUEBLE.ID_INMUEBLE=SERVICIO_ADICIONAL.ID_INMUEBLE_SE AND (SERVICIO_ADICIONAL.NOMBRE='SPA' OR SERVICIO_ADICIONAL.NOMBRE='RESTAURANTE' OR SERVICIO_ADICIONAL.NOMBRE='SAUNA')
GROUP BY INMUEBLE.ID_INMUEBLE)
 ON INMUEBLES_RESERVADOS=INMUEBLES
 WHERE INMUEBLES_RESERVADOS IS NULL
 ;


////////////////////////////////////PRUEBAS DE UNICIDAD TABLA INMUEBLE///////////////////

//insercion tupla correcta
INSERT INTO INMUEBLE (ID_INMUEBLE, DISPONIBLE,NOMBRE,TIPO_INMUEBLE,UBICACION,CAPACIDAD,DESCRIPCION,VECES_RESERVADA,COSTO_NOCHE,ID_OPERADOR)
VALUES (11, 'Y','HABITACION BUEN VIVIR','HABITACION_HOSTEL','CRA 26 #68C-45',2,'2 CAMAS UN BAÑO',2,150,'1007863899')
//insersion tupla incorrecta
INSERT INTO INMUEBLE (ID_INMUEBLE, DISPONIBLE,NOMBRE,TIPO_INMUEBLE,UBICACION,CAPACIDAD,DESCRIPCION,VECES_RESERVADA,COSTO_NOCHE,ID_OPERADOR)
VALUES (11, 'Y','HABITACION manuela','HABITACION_HOSTEL','CRA 25 #68C-45',2,'2 CAMAS UN BAÑO',2,150,'1007863899')

///////////////////////////////////PRUEBAS DE INTEGRIDAD CON FK///////////////////////////

//inserción tupla correcta
INSERT 
INTO HABITACION_HOSTEL (COMPARTIDA,ID_INMUEBLE_HSH)
VALUES('Y',11)

//inserción tupla INcorrecta(id 16 en inmueble no existe)
INSERT
INTO VIVIENDA_CEDIDA (DIAS_USADO_AÑO,SEGURO,ID_INMUEBLE_VC)
VALUES(3,'INFO SEGURO MAPFRE',16)

//BORRADO DE UNA TUPLA MAESTRA DE LAS UQ EOTRAS DEPENDEN,BORRAREMOS UN TUPLA DE INMUEBLE
DELETE FROM INMUEBLE
WHERE ID_INMUEBLE = 2


//////////////////////////PRUEBAS DE INTEGRIDAD DE ACUERO CON RESTRICCIONES DE CHEQUEO/////////////////////////

//INSERCION INCORRECTA, VIOLA EL CHECH DEL CAMPO
INSERT INTO INMUEBLE (ID_INMUEBLE, DISPONIBLE,NOMBRE,TIPO_INMUEBLE,UBICACION,CAPACIDAD,DESCRIPCION,VECES_RESERVADA,COSTO_NOCHE,ID_OPERADOR)
VALUES (12, 'TRUE','HABITACION BUEN VIVIR','HABITACION_HOSTEL','CRA 26 #68C-45',2,'2 CAMAS UN BAÑO',2,150,'1007863899')







  
 
 


